### ISSUE TITLE
byte array is returned in mock for JpaRepository method while entity is expected

### ISSUE THREAD

**Issue by alisevych** [UnitTestBot/UTBotJava#2630] opened 2023-09-29 17:18 UTC
**Description**

byte array is returned in mock for JpaRepository method while entity is expected
Test is not compiling

**To Reproduce**

1. Install [UnitTestBot plugin built from main](https://github.com/UnitTestBot/UTBotJava/actions/runs/6310940119) in IntelliJ IDEA
2. Open `Medical-Web-App` project, develop-new branch
3. Generate Unit tests for `NotificationService` with @SpringBootApplication configuration

**Expected behavior**

Compiling tests should be generated

**Actual behavior**

byte array is set to be returned from JpaRepository<T, ID> getById method mock,
while UserRepository extends it with T = User
3 similar tests are not compiling.

**Screenshots, logs**

```
@Repository
public interface UserRepository extends JpaRepository<User, Long>
```
```
public interface JpaRepository<T, ID>
```
```
    T getById(ID id);
```
~~~java
    @Test
    @DisplayName("getAllNotifications: user = userRepository.getById(user_id) : True -> ThrowClassCastException")
    public void testGetAllNotifications_ThrowClassCastException() {
        byte[] byteArray = {};
        (when(userRepositoryMock.getById(any()))).thenReturn(byteArray);
        
        /* This test fails because method [com.app.medicalwebapp.services.NotificationService.getAllNotifications] produces [java.lang.ClassCastException: class [B cannot be cast to class com.app.medicalwebapp.model.User ([B is in module java.base of loader 'bootstrap'; com.app.medicalwebapp.model.User is in unnamed module of loader org.utbot.instrumentation.process.HandlerClassesLoader @10eb7238)]
            com.app.medicalwebapp.repositories.UserRepository$MockitoMock$YIpF9DQ3.getById(Unknown Source)
            com.app.medicalwebapp.repositories.UserRepository$MockitoMock$YIpF9DQ3.getById(Unknown Source)
            com.app.medicalwebapp.services.NotificationService.getAllNotifications(NotificationService.java:54) */
        notificationService.getAllNotifications(null);
    }

~~~

**Environment**

IntelliJ IDEA version - Ultimate 2023.2
Project - Maven
JDK - 11

**Comment by IlyaMuravjov** [comment] 2023-09-29 18:02
Looks like a duplicate of #2367

**Closed** 2023-10-02 07:53 UTC
Labels: ctg-bug, status-duplicate, comp-symbolic-engine, comp-spring
