### ISSUE TITLE
Test generation for an abstract class fails

### ISSUE THREAD

**Issue by sergeypospelov** [UnitTestBot/UTBotJava#873] opened 2022-09-08 06:55 UTC
**Description**

If we run test generation for an abstract class, the dialog appears, but further test generation fails.

**To Reproduce**

1. Create a Java project
2. Paste this code:
```java
abstract public class AbstractClass {
    int testMe(int x) {
        if (x == 0) {
            throw new IllegalStateException("123");
        }
        return 0;
    }
}
```
3. Run "Create Tests with UtBot" action
4. Doesn't matter mocks enabled or not
5. Choose the single method and press "Generate Tests" button

**Expected behavior**

I see these possible behaviors:
- Prohibit to generate tests for abstract classes completely, so action is disabled, if the caret context class is abstract
- Prohibit to generate tests for abstract classes completely, so popup appears if the user tries to run the action for an abstract class
- Allow to generate tests for abstract classes if mocks are enabled, and initialize an abstract class instance with mocks

Maybe there are better solutions.

**Actual behavior**

An error popup appears saying nothing about the class is abstract.

**Visual proofs (screenshots, logs, images)**

![image](https://user-images.githubusercontent.com/30112817/189054719-e2186048-67dc-4825-b38c-aa012e5ad245.png)

**Comment by Vassiliy-Kudryashov** [comment] 2022-09-14 12:09
Looks like ~duplicate of https://github.com/UnitTestBot/UTBotJava/issues/221

**Closed** 2022-10-06 10:28 UTC
Labels: bug
