### ISSUE TITLE
Exception is thrown when trying to generate a test for the "accelerate" method below

### ISSUE THREAD

**Issue by max-arshinov** [UnitTestBot/UTBotJava#616] opened 2022-07-29 20:54 UTC
```
@Component
public class Car {
    private final Engine engine;
    private final Transmission transmission;
    private final Weels weels;

    public Car(Engine engine, Transmission transmission, Weels weels) {
        this.engine = engine;
        this.transmission = transmission;
        this.weels = weels;
    }

    public void drive(){
        this.engine.start();
        this.transmission.setSpeed(1);
        this.accelarate(10);
        this.transmission.setSpeed(3);
        this.accelarate(60);
        this.transmission.setSpeed(4);
    }

    public int accelerate(int i) {
        return i;
    }

    public Engine getEngine() {
        return engine;
    }
}
```

```
ava.net.URISyntaxException: Illegal character in path at index 35: file:/Users/..../Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/221.6008.13/IntelliJ IDEA.app.plugins/utbot-intellij/lib/utbot-framework-2022.7-beta.jar
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3114)
	at java.base/java.net.URI.<init>(URI.java:600)
	at org.utbot.common.FileUtil.extractJarName(FileUtil.kt:108)
	at org.utbot.common.FileUtil.isolateClassFiles(FileUtil.kt:94)
	at org.utbot.framework.plugin.api.SootUtilsKt.runSoot(SootUtils.kt:61)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator.init(UtBotTestCaseGenerator.kt:111)
	at org.utbot.intellij.plugin.generator.CodeGenerator.<init>(CodeGenerator.kt:44)
	at org.utbot.intellij.plugin.generator.CodeGenerator.<init>(CodeGenerator.kt:36)
	at org.utbot.intellij.plugin.ui.UtTestsDialogProcessor$createTests$2$1.run(UtTestsDialogProcessor.kt:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by max-arshinov** [comment] 2022-07-29 20:56
![image](https://user-images.githubusercontent.com/820550/181841850-0c046a7d-ed29-49c5-9174-31adc2b45ef7.png)

![image](https://user-images.githubusercontent.com/820550/181841906-7edfd28e-0684-4537-a743-18c5893e0184.png)

**Comment by Vassiliy-Kudryashov** [comment] 2022-08-09 15:15
It seems to be macOS-specific issue, cannot reproduce it under Windows.

**Comment by Vassiliy-Kudryashov** [comment] 2022-08-09 21:09
Issue looks like duplicate of #587

**Closed by Vassiliy-Kudryashov** 2022-08-09 21:09 UTC
