### ISSUE TITLE
UTBot from Idea Marketplace plugin throws exception and doesn't generate tests

### ISSUE THREAD

**Issue by rmzs0711** [UnitTestBot/UTBotJava#653] opened 2022-08-03 11:00 UTC
**Description**
At my first try I was using JDK 17 and met this exception, so then I downgraded my jdk version, recompiled project, reinstalled plugin, but it didn't help to me

**Steps to reproduce**

1. Install plugin from Idea marketplace
2. Run the project in IntelliJ Idea
3.  Generate tests in TrieImpl.java

**Expected behavior**

 Tests are supposed to be generated.

**Actual behavior and visual proofs (screenshots, logs, images)**

```
java.lang.IllegalArgumentException: Unsupported class file major version 61
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:284)
	at soot.asm.AsmClassSource.resolve(AsmClassSource.java:64)
	at soot.SootResolver.bringToHierarchyUnchecked(SootResolver.java:253)
	at soot.SootResolver.bringToHierarchy(SootResolver.java:221)
	at soot.SootResolver.bringToSignatures(SootResolver.java:292)
	at soot.SootResolver.bringToBodies(SootResolver.java:332)
	at soot.SootResolver.processResolveWorklist(SootResolver.java:171)
	at soot.SootResolver.resolveClass(SootResolver.java:141)
	at soot.Scene.tryLoadClass(Scene.java:965)
	at soot.Scene.loadBasicClasses(Scene.java:1670)
	at soot.Scene.loadNecessaryClasses(Scene.java:1770)
	at org.utbot.framework.plugin.api.SootUtilsKt.runSoot(SootUtils.kt:80)
	at org.utbot.framework.plugin.api.UtBotTestCaseGenerator.init(UtBotTestCaseGenerator.kt:111)
	at org.utbot.intellij.plugin.generator.CodeGenerator.<init>(CodeGenerator.kt:44)
	at org.utbot.intellij.plugin.generator.CodeGenerator.<init>(CodeGenerator.kt:36)
	at org.utbot.intellij.plugin.ui.UtTestsDialogProcessor$createTests$2$1.run(UtTestsDialogProcessor.kt:157)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:252)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:252)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Environment**
`java -version`
```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~20.04-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```
JUnit 5

IntelliJ IDEA 2022.2 (Ultimate Edition)
Build #IU-222.3345.118, built on July 26, 2022

Runtime version: 17.0.3+7-b469.32 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Linux 5.15.0-41-generic
GC: G1 Young Generation, G1 Old Generation
Memory: 1922M
Cores: 12
Non-Bundled Plugins:
    com.markskelton.one-dark-theme (5.6.0)
    com.jetbrains.darkPurpleTheme (1.3)
    com.jetbrains.CyanTheme (1.3)
    com.intellij.ideolog (203.0.30.0)
    com.github.oowekyala.javacc (1.10)
    com.elliotwaite.cyberpunk_theme (1.0.12)
    Rider UI Theme Pack (0.10.1)
    Pythonid (222.3345.131)
    org.utbot.intellij.plugin.id (2022.7-beta)

Kotlin: 222-1.7.10-release-334-IJ3345.118
Current Desktop: ubuntu:GNOME

**Additional context**

@alisevych please review

**Comment by rmzs0711** [comment] 2022-08-03 11:02
[Gradle18Test.zip](https://github.com/UnitTestBot/UTBotJava/files/9250713/Gradle18Test.zip)

**Comment by alisevych** [comment] 2022-08-03 13:28
@rmzs0711 
Please take the Bug template - and follow it. "Steps to reproduce" instead of "To reproduce" an etc.
Add the information about Environment : OS, IDEA version.
Include information about JDK 17 used for the project first - in the steps.

**Comment by rmzs0711** [comment] 2022-08-03 15:04
@alisevych done

**Comment by alisevych** [comment] 2022-08-03 15:38
@rmzs0711 
Now I see that that you're using IntelliJ IDEA with JRE 17 - and it's incompatible with UTBotJava plugin currently.
Nevertheless your project code is compiled with JDK 8.
So it's duplicate of: https://github.com/UnitTestBot/UTBotJava/issues/481

**Closed by alisevych** 2022-08-03 15:38 UTC
Labels: bug, duplicate
