### ISSUE TITLE
UtUtils class with Mockito support is overwritten with a regular UtUtils class

### ISSUE THREAD

**Issue by olganaumenko** [UnitTestBot/UTBotJava#1179] opened 2022-10-18 20:55 UTC
**Description**

If you have previously generated tests with mocking, the next `UtUtils` class should support mocking as well — even if there is no need for mocking during current generation, so that existing tests could still rely on the proper methods from `UtUtils` class.

In _UnitTestBot 2022.10.439_ UtUtils class with Mockito support is overwritten with a regular UtUtils class (without mocking support).

**To Reproduce**

1. Install _UnitTestBot 2022.10.439_ as the IntelliJ IDEA plugin.
2. Generate tests for the `CommonMocksExample.java` class with **Mock everything outside the class** enabled.
3. Go to your **Test sources root** and find the `UtUtils` class with a comment:

>` // This is UtUtils class with Mockito support`

5. Generate tests for the `QueueUsages.java` with **Do not mock** enabled.
6. Go to your **Test sources root** and find the `UtUtils` class with a comment: 

> `// This is a regular UtUtils class (without mock framework usage)`

**Expected behavior**

After generating tests for the `QueueUsages.java` with **Do not mock** enabled the previously generated UtUtils class with Mockito support is not overwritten with a regular UtUtils class.

**Actual behavior**

UtUtils class with Mockito support is overwritten with a regular UtUtils class (without mocking support).

**Visual proofs (screenshots, logs, images)**

![Ututils222](https://user-images.githubusercontent.com/64418523/196541950-85a98040-97f6-4273-80fb-2ae7e6a11c2c.PNG)

![Ututils333](https://user-images.githubusercontent.com/64418523/196541981-585d6e6c-0d91-48f7-b44e-be480d4f6763.PNG)

**Environment**

Windows 10 Pro
IntelliJ IDEA 2022.2.3 (Ultimate Edition)
_UnitTestBot 2022.10.439_
JDK 11

**Comment by tyuldashev** [comment] 2022-11-22 12:31
Duplicate of this case - #1378, was fixed and verified, so this one could be closed too.

**Closed by tyuldashev** 2022-11-22 12:31 UTC
Labels: bug
