### ISSUE TITLE
Do not mock entitities in Spring unit tests

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2222] opened 2023-05-22 07:05 UTC
**Description**

Current mocking and type replacement strategy leads to mocking classes annotated as `@Entity` in Spring unit tests.
However, it is useless, we should not mock Entity classes.

**Comment by alisevych** [comment] 2023-07-03 13:50
duplicate of #2341

**Closed** 2023-07-03 13:50 UTC
Labels: ctg-enhancement, comp-symbolic-engine, comp-spring
