### ISSUE TITLE
ClassNotFoundException: java.util.regex.Pattern$$Lamda$25

### ISSUE THREAD

**Issue by alexeyfridman** [UnitTestBot/UTBotJava#108] opened 2022-06-01 10:27 UTC
UTBotJava version: 1.0-20220422.094606-11
project under test: UTBotTest
file under test: StringRegex

**Comment by dtim** [comment] 2022-09-07 11:17
Is that a duplicate of #174?

**Comment by Damtev** [comment] 2022-09-13 10:44
Cannot reproduce

**Closed** 2022-09-14 07:28 UTC
Labels: bug, top focus
