### ISSUE TITLE
Variables are not created in the Spring generated code

### ISSUE THREAD

**Issue by EgorkaKulikov** [UnitTestBot/UTBotJava#2108] opened 2023-04-07 06:37 UTC
**To Reproduce**

Generate tests for method `PetTypeFormatter.parse` from https://github.com/spring-projects/spring-petclinic
Do not change any settings, just Ctr+Shift+L and OK

**Expected behavior**

Test class is compilable

**Actual behavior**

One of generated methods contains uninitialized variables, so there are compilation errors.

```java
@Test
	@DisplayName("parse: OwnerRepositoryFindPetTypes -> return type")
	public void testParse_TypeGetNameEquals() throws ParseException, ClassNotFoundException, IllegalAccessException, NoSuchFieldException, InvocationTargetException, NoSuchMethodException {

		(when(ownerRepositoryMock.findPetTypes())).thenReturn(arrayList);

		PetType actual = petTypeFormatter.parse(string, ((Locale) null));

		PetType expected = new PetType();
		expected.setName("");
		String expectedName = ((String) getFieldValue(expected, "org.springframework.samples.petclinic.model.NamedEntity", "name"));
		String actualName = ((String) getFieldValue(actual, "org.springframework.samples.petclinic.model.NamedEntity", "name"));
		assertEquals(expectedName, actualName);

		Integer actualId = ((Integer) getFieldValue(actual, "org.springframework.samples.petclinic.model.BaseEntity", "id"));
		assertNull(actualId);

	}
```

**Additional context**

Uninitialized variables are `arrayList` and `string`. There names looks like erronous too.

**Comment by alisevych** [comment] 2023-04-07 10:49
duplicate of 
- #2107

**Closed** 2023-04-07 15:17 UTC
Labels: ctg-bug, status-duplicate, comp-codegen, comp-spring
